backend:
  name: github
  repo: YusukeSuzuki1213/new-portfolio
y
media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "posts"
    label: "Posts"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "title", name: "title", widget: "string" }      
      - { label: "summary", name: "summary", widget: "date" }
      - { label: "src", name: "src", widget: "markdown" }  
      - { label: "date(e.g, )", name: "date", widget: "markdown" }
      - { label: "categories", name: "categories", widget: "markdown" }
      - { label: "tags", name: "tags", widget: "markdown" }


